# Generated by Django 4.0.4 on 2023-05-04 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
